# Этот рабочий процесс использует действия, которые не сертифицированы GitHub.
# Они предоставляются сторонним поставщиком, и на них распространяются
# отдельные условия обслуживания, политика конфиденциальности и поддержка
# документации.

# GitHub рекомендует закрепить действия в фиксации SHA.
# Чтобы получить более новую версию, потребуется обновить SHA.
# Вы также можете ссылаться на тег или ветвь, однако действие может измениться без предупреждения.

name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Make Gradlew Executable
        run: chmod +x ./gradlew
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@ccb4328a959376b642e027874838f60f8e596de3
      - name: Build with Gradle
        uses: gradle/gradle-build-action@749f47bda3e44aa060e82d7b3ef7e40d953bd629
        with:
          arguments: build

      - name: Run Checkstyle
        run: ./gradlew checkstyleMain

      - name: Upload Checkstyle report
        uses: actions/upload-artifact@v2
        with:
          name: checkstyle-report
          path: build/reports/checkstyle/main.html

      - name: Run unit tests
        run: ./gradlew test

      - name: Save test report
        uses: actions/upload-artifact@v2
        with:
            name: test-report
            path: build/reports/tests/test/index.html

      - name: Build JAR
        run: ./gradlew jar

